### ISSUE TITLE
Free open source Plugin for Joomla JCE core

### ISSUE THREAD

**Issue by uglyeoin** [Milglius/resizeonupload#2]
Please be aware that JCE is not part of core but an add on

You would be better off making a TinyMCE plugin. TinyMCE is great anyway. JCE is based on it I think.

I can't wait to see what you develop

**Comment by Milglius** [comment]
Our aim is to create Free Open source plugin whick enables Joomla jce core to automaticaly resize image. 

Its quite small job, but will give big reward to joomla users who can't afford paid joomla plugin.

uglyeoin you dont need to wait you can join in and help us develop this plugin. Please let us know how you can help here.

tinymce is huge job with many software developers in need, we think Joomla jce core is best option nowwe just need create simple plugin that lets automaticaly resize image on upload for article. Thats all this plugin is for

I'm trying to set realistic expectations for how things should be done.

**Comment by uglyeoin** [comment]
I know it's just wording, but your wording is incorrect.  If you say something incorrect people will misunderstand and you will spend time debating things that you don't need to debate.

JCE is not part of the core.  Tiny MCE is part of the core.  If you want to submit something to the core of Joomla! then it will need to be Tiny MCE or it will not be accepted.  

Nobody in Joomla! would accept something that is part of an extension for the core.  That should be submitted as an extension.  So if it is for JCE then you would have to add it to the JED.  

Possibly it should be related to the media manager and not any editor.

I don't know how big the job is, but I don't have time at the moment, possibly not the skills either.  But I am glad you are so passionate about it.  Since you say it is a small job I will follow this repository with interest.  I can't wait to see how quickly you complete it.

**Comment by Milglius** [comment]
We want to create Free resize on upload open source plugin for Joomla JCE core extension. The wording is correct. 

If you want to use Free resize on upload open source plugin for Joomla JCE core extension you need to have Joomla cms and JCE Core extension installled.

How quickly we complete developing this plugin depends on how many joomla developers participate, couse now we have outdated joomla cms without posibility to resize image on upload for free for all joomla users.

The problem we face now is:
Try to add 5 pictures to Joomla JCE Core article and you easily can get published fronted 1 article with 25 MB size. Joomla cms JCE Core claims to be A Content Editor for Joomla but can't resize image for free, We dont think 30MB + article is normal thing for modern Joomla Core JCE only for outdated or buggy Joomla cms it should be normal. Hope you agree and help us create such plugin to solve this issue.

**Comment by uglyeoin** [comment]
One of the issues with your statement is that some people woukd want a 30gb image for example a designer, artist or photographer may wish to upload the original file for one reason or another. 

There are better ways, such as hosting elsewhere but not everyone will want to do that. 

My basic point is I know you see this as a bug bit it isn't necessarily. And resizing before upload would be my recommendation so you can crop it the way you want it. You could also compress it. 

Furthermore, you would need to resize for mobile, tablet etc as all of those things would need different image sizes ideally using srcset. 

Just some thoughts as you are developing the plugin.

**Comment by Milglius** [comment]
uglyeoin your sugestion is good but first we need to create plugin which can resize on upload (for exampe 3MB, 6MB or 10 MB) image. This is huge issue and total waste. Untill we have this free plugin.

Using srcset is modern solution for cms, but as we know joomla cms dont use srcset as I said this is big sign of outdated cms. But the problem with joomla is even bigger couse joomla cms can't even resize image on upload. 

If joomla user try to add 3 pictures (for example 1 picture = 9MB ) to Joomla JCE Core article and you easily can get published fronted 1 article with 30 MB size. 

If we create plugin to resize on upload and try to add 3 picture (for example 1 picture = 9MB and resize pictures on upload, for example 1 picture resizedon upload to 100 Kb) to Joomla JCE Core article using Free Resizeonupload plugin and you easily can get published fronted 1 article with 300 KB size. 

Using outdated joomla cms you have 1 article 30MB size
VS.
Using outdated joomla cms + jce core extension + Free Resizeonupload plugin you have 1 article 30KB size

1 article and diference 30 MB vs 300KB

**Comment by uglyeoin** [comment]
Yes, I see the issue you are tryint Ng to solve. Well, good luck with it. I look forward to seeing the results.

**Comment by Milglius** [comment]
Thank you. I hope joomla developers participate and commit their code to Free resize on upload open source plugin for Joomla JCE core extension.

**Comment by uglyeoin** [comment]
Are you doing any of the development yourself?

**Comment by Milglius** [comment]
uglyeoin please dont adwertise paid software here.

uglyeoin it depends on what joomla want to be now joomla is abandoned software joomla user needs to spent more then 1000 € on wariuos extensions to have mediocre cms.

**Comment by uglyeoin** [comment]
Honestly, I don't agree.  I don't spend anywhere near that money when I build a site.  And Joomla! works great for my needs.  Happy not to "advertise" any paid extensions.  I have no affiliation with any of them, I was trying to be polite about their work and grateful for them providing it at a cheap price.  

I know when I have used other CMS I have found almost everything to be much more expensive.  And missing a lot of features Joomla! has.  But I'm not here to debate it with you, you have your opinion and I have mine.  

I guess every user has a different use case.  I build sites for lots of people.  All of them seem happy with the outcome.  But all of them expect to make more than €1,000.  Perhaps you could search the JED for free extensions?  Many exist.

**Comment by Milglius** [comment]
Jed has lots of abandoned extensions that no one supports or fix bug. 

Using outdated joomla 3.9.10 cms you can have 1 article 50 MB size with just 5 pictures, I disagree that anyone can be happy with the outcome. To fix this you need paid plugins. We think it should be fixed with free plugin.

we need just 1 Free resize on upload open source plugin for Joomla JCE core extension and on jed you can find 0 free extensios that could do resize on upload open source plugin for Joomla JCE core extension

**Comment by uglyeoin** [comment]
JED doesn't really have that many abandoned extensions.  I believe they get removed regularly, or if a vulnerability is found.  But I'm sure there are some.  I certainly wouldn't use anything outdated.  They removed all of the Joomla! 2.5 extensions that were not Joomla! 3 compatible in one go.  That was a heck of a lot of extensions.  Perhaps if you are not receiving support for a free extension it is because of the way you are asking?

Someone will have a use case for larger images, but you're right, I think most of the time it's not ideal.  

**Here's one workflow to achieve this**

Resize before uploading.  This is my preferred choice if I'm honest as I can control the size in mb, the quality in compression, but also, I like my website to have a certain style, so I prefer all of the blog images for example to have a set size in pixels.  But I like to resize it before I upload it so I can crop the image myself so nobody gets their head chopped or anything like that.

It's not just the physical size in pixels you want to reduce, but also to compress it.  In many cases you would prefer PNGs to be JPGs as they are a lot smaller.  Gifs can be quite large too.

I understand that might not be ideal for novice users.  But here is a free image resizer.  https://picresize.com.  Sorry if you feel that is advertising.  Again I have no affiliation with the website I'm just trying to help you solve your problem (for free).   

If you do an override of the front end editing or administrator you can easily give your users instructions on how to resize and what size to make images.  I have done this on many projects.  In some projects I provided a video tutorial to explain it and that meant all users had an easy way to comply.

You can also reduce the file size allowed to be uploaded which would mean any user would not be able to upload huge images and would be forced to resize them.  By limiting the file size you would have a way to avoid most of this problem with "outdated" Joomla! core quite easily.  It isn't unusual for a website to tell me I cannot upload a large image, I see that all the time.

Maybe that workflow would be a free way of you getting your desired result?  It seems that you want someone to code things perfectly for your need for free, but it's a lot of time and people have jobs, families, hobbies, and other things they are doing.  

Even if images are resized, to only 200kb, there is really nothing stopping users from adding 100 images or a huge gallery or some sort.  That sort of plugin would be completely different from an image resizer.  

There are lots of ways of doing things in "outdated" powerful Joomla!  Take some time to ask people, look around, read up on things.

**Comment by Milglius** [comment]
uglyeoin please dont adwertise non joomla solution here.

You just need joomla properly use image libraries (like image magik or gd) for php on your server, most have them. So if joomla lacks this simple feature (even GitHub here can resize image, and dont ask his uses go to some site to resize image and then go back to him) it just means joomla is abandoned software.

Free resize on upload open source plugin for Joomla JCE core extension is the only way to go and have resize on upload for free for joomla users.

**Comment by uglyeoin** [comment]
I mean... all the evidence points to it not being abandoned software.  Especially because you are going to develop this feature.  I honestly think it's fantastic that you are making such a great contribution to the open source community.  It will really benefit everyone.  I can't wait to see it.  Are image magik or gd part of the Joomla! minimum specifications or will you need to update them and the documentation to go with it?

**Comment by Milglius** [comment]
How quickly we complete developing this plugin depends on how many joomla developers participate, couse now we have outdated joomla cms without posibility to resize image on upload for free for all joomla users. All the evidence points to joomla being abandoned software.

You can see the code its open source, Now time to test this plugin and and submit bugs if any you can find.

Free resize on upload open source plugin for Joomla JCE core extension is the only way to go and have resize on upload for free for joomla users.

Now every joomla developer can test the code and hunt for bugs. Now you can see what we are developing for all joomla users for free. The code is here, now we need to test it. Please join and help abandoned joomla users.
